locale: ko-kr
title: Zero to Hero
#description: 저장소
url: https://doubleu0714.github.io
baseurl: ""
theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme"
date_format: "%Y-%m-%d"
search_full_content: true

author:
  name: Wonhyung park
  picture: /images/iam.jpg

google_fonts:
  - name: "Do Hyeon"
  - name: "Nanum Gothic"